name: test GitHub Action
on:
  workflow_dispatch:


jobs:
  testjob:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: wechuli/actionsutils@main
        with:
          tasks: oidctoken
  
      - uses: wechuli/actionsutils@main
        with:
          tasks: 'oidctoken,context'
          audience: 'fakeaudience'
          create-artifact: true
